# Change these first
owner: samuelemusiani # Your GitHub organization or username, where this repository lives
repo: status.adm # The name of this repository

sites:
  - name: saragozza
    url: saragozza.students.cs.unibo.it
    check: "tcp-ping"
    port: 22
    assignees:
      - samuelemusiani

  - name: Adm website
    url: https://students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Git
    url: https://git.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: LDAP website
    url: https://ldap.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Netbox
    url: https://netbox.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Semaphore
    url: https://ansible.students.cs.unibo.it
    assignees:
      - samuelemusiani

  # csunibo staff
  - name: Dynamik
    url: https://risorse.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: CSUnibo website
    url: https://csunibo.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Calendar website
    url: https://calendar.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Media
    url: https://media.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Registrate
    url: https://registrate.students.cs.unibo.it
    headers:
      - "Authorization: Basic $REGISTRATE_AUTH"
    assignees:
      - samuelemusiani

  - name: Dumbo
    url: https://dumbo.students.cs.unibo.it
    assignees:
      - samuelemusiani
      
  - name: VMID
    url: https://vm.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Fileseeker
    url: https://dav.students.cs.unibo.it
    expectedStatusCodes:
      - 405
    assignees:
      - samuelemusiani

  - name: Underleaf
    url: https://underleaf.students.cs.unibo.it
    assignees:
      - samuelemusiani

  - name: Sasso
    url: https://sasso.students.cs.unibo.it
    assignees:
      - samuelemusiani

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status2.students.cs.unibo.it
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime adm
  introTitle: "**Upptime** for adm"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/samuelemusiani/status.adm).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
